### ISSUE TITLE
"electron-packager" dependency needs a version bump to run w/ Node v10+

### ISSUE THREAD

**Issue by warren-bank** [yuya-oc/electron-scaffold#1]
just a heads up..

* error:
  ```text
    CANNOT RUN WITH NODE 10.14.2
    Electron Packager requires Node 4.0 or above.
  ```
* [issue](https://github.com/electron-userland/electron-packager/issues/863)
* fix: `"electron-packager": "^12.2.0"`

**Comment by yuya-oc** [comment]
Thanks to let me know. I've updated with `"electron-packager": "*"`. (47ef0d9b79cf34b51314fc49f0987e375401af5c)
